v8.2.0 manual
conda-forge/copier-feedstock pull request #13
Opened 2023-09-01 20:29 UTC by thewchan

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2023-09-01 20:30 UTC, thewchan commented
@conda-forge-admin, please rerender

2023-09-01 22:59 UTC, thewchan commented
@fcollonval @kir0ul review and merge request, thanks!

2023-09-05 08:16 UTC, fcollonval requested changes
Thanks @thewchan 

Would you mind opening a fix upstream for `prompt_toolkit`?

2023-09-05 08:16 UTC, fcollonval commented on recipe/meta.yaml
> +    - prompt_toolkit <=3.0.36,>=2.0
```suggestion
```

Could you open an PR to fix this upstream at https://github.com/conda-forge/questionary-feedstock
as we should avoid adding indirect dependency constraints to reduce maintenance and ease the env solver job.

2023-09-11 07:07 UTC, fcollonval commented on recipe/meta.yaml
> +    - prompt_toolkit <=3.0.36,>=2.0
Fixed upstream by https://github.com/conda-forge/questionary-feedstock/pull/7

2023-09-11 07:10 UTC, fcollonval commented on conda-forge.yml
> +  inspection: hint-all
Please don't take initiative to change recipe configuration in upgrade PR except if needed.

```suggestion
  automerge: true
  inspection: hint-all
```

2023-09-11 07:12 UTC, fcollonval commented on recipe/meta.yaml
> +    - typing-extensions >=3.7.4,<5.0.0
Same here - git is available on conda (not on PyPI). Please don't change pure conda dependencies in upgrade PR except if needed - these changes must be discussed as they may break consumer workflow.

```suggestion
    - git >=2.27
    - typing-extensions >=3.7.4,<5.0.0
```

2023-09-11 07:45 UTC, fcollonval approved these changes

2023-09-11 07:45 UTC, merged